version: '3'
services:
  winestore-postgresql-demo:
    container_name: api-container-postgresql
    build: "."
    ports:
        - "8081:8081"
    depends_on:
        - postgresqldb
    restart: always

  postgresqldb:
    container_name: postgresqldb
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=winestore
    restart: always
    ports:
      - "5432:5432"