version: '3'
services:
  winestore-mysql-demo:
    container_name: api-container-mysql
    build: "."
    ports:
        - "8080:8080"
    depends_on:
        - mysqldb
    restart: always
    
  mysqldb:
    container_name: db-container-mysql
    image: mysql:5.7
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=winestore
    restart: always

