version: "2"
services:
  postgresql:
    container_name: demo-postgresql
    image: postgres:latest
    restart: always
    volumes:
      - demo-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=winestore
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
  demo:
    build: "./"
    container_name: demo-api
    restart: always
    volumes:
            - ./:/home/node/app
    ports:
            - "8080:8080"
    depends_on:
            - postgresql
        
volumes: 
  demo-postgresql: {}