version: "2"
services:
  mysql:
    container_name: demo-mysql
    image: mysql:5.7
    restart: always
    volumes:
        - demo-mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=winestore
    ports:
        - 8888:8888

  demo:
    build: "./"
    container_name: demo-api
    restart: always
    volumes:
            - ./:/home/node/app
    ports:
            - "8080:8080"
    depends_on:
            - mysql

volumes:
    demo-mysql: {}