version: '2'
services:
    postgresql:
        container_name: winestore-postgresql
        image: postgres:latest
        volumes:
            - winestore-postgresql:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=postgres
            - POSTGRES_DB=winestore
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    winestore-postgresql: {}