version: '2'
services:
    db:
        container_name: winestore-postgresql
        image: postgres:latest
        volumes:
            - winestore-postgresql:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=postgres
            - POSTGRES_DB=winestore
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
    db2:
        container_name: winestore-mysql
        image: mysql:5.7
        volumes:
            - winestore-mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=winestore
        ports:
            - 8888:8888

volumes:
    winestore-postgresql: {}
    winestore-mysql: {}
